version: 2

jobs:
  "build debug":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - restore_cache:
          key: debug-cache
      - run:
            name: Build
            command: cargo build
      - save_cache:
          key: debug-cache
          paths:
            - "~/.cargo"
            - "./target"

  "build release":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - restore_cache:
          key: release-cache
      - run:
            name: Build
            command: cargo build --release
      - save_cache:
          key: release-cache
          paths:
            - "~/.cargo"
            - "./target"

  "store debug artefacts":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - run: |
          mkdir artefacts/
          cp -R ./templates ./artefacts/
      - restore_cache:
          key: debug-cache
      - run: cp -R ./target/debug/blog ./artefacts/
      - store_artefacts:
          path: ./artefacts/
          destination: debug-artefact

