version: 2

jobs:
  "build debug":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - restore_cache:
          key: debug-cache
      - run:
            name: Build
            command: cargo build
      - save_cache:
          key: debug-cache
          paths:
            - "~/.cargo"
            - "./target"

  "build release":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - restore_cache:
          key: release-cache
      - run:
            name: Build
            command: cargo build --release
      - save_cache:
          key: release-cache
          paths:
            - "~/.cargo"
            - "./target"

  "store debug artifacts":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - run: |
          mkdir artifacts/
          cp -R ./templates ./artifacts/
      - restore_cache:
          key: debug-cache
      - run: cp -R ./target/debug/blog ./artifacts/
      - store_artifacts:
          path: ./artifacts/
          destination: debug-artifact

workflows:
  version: 2
  build:
    jobs:
      - build debug
      - build release
      - store debug artifacts:
          requires:
            - build debug
        
