version: 2

jobs:
  "build debug":
    docker:
      - image: rust:1.38.0-alpine3.10

    steps:
      - checkout
      - restore_cache:
          key: debug-cache
      - run:
            name: Build
            command: |
              mkdir ./artifacts
              cargo build
              cp ./target/debug/blog ./artifacts/
              cp -R ./templates ./artifacts/templates
              tar c -zf debug.tar.gz ./artifacts/*
      - store_artifacts:
          path: ./debug.tar.gz
          destination: debug-artifact.tar.gz
      - save_cache:
          key: debug-cache
          paths:
            - "~/.cargo"
            - "./target"

  "build release":
    docker:
      - image: rust:1.38.0-alpine3.10

    steps:
      - checkout
      - restore_cache:
          key: release-cache
      - run:
            name: Build
            command: |
              mkdir ./artifacts
              cargo build --release
              cp ./target/release/blog ./artifacts/
              cp -R ./templates ./artifacts/templates
              tar c -zf release.tar.gz ./artifacts/*
      - store_artifacts:
          path: ./release.tar.gz
          destination: release-artifact.tar.gz
      - save_cache:
          key: release-cache
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2
  build:
    jobs:
      - build debug
      - build release
