version: 2

jobs:
  "build debug":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - restore_cache:
          key: debug-cache
      - run:
            name: Build
            command: |
              rm -rf ./artifacts
              mkdir ./artifacts
              cargo build --out-dir ./artifacts/ -Z unstable-options
      - save_cache:
          key: debug-cache
          paths:
            - "~/.cargo"
            - "./target"
            - "./artifacts"

  "build release":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - restore_cache:
          key: release-cache
      - run:
            name: Build
            command: |
              rm -rf ./artifacts
              mkdir ./artifacts
              cargo build --release --out-dir ./artifacts/ -Z unstable-options
      - save_cache:
          key: release-cache
          paths:
            - "~/.cargo"
            - "./target"
            - "./artifacts"

  "store debug artifacts":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout
      - restore_cache:
          key: debug-cache
      - run: |
          cp -R ./templates ./artifacts/
          tar c -zf debug.tar.gz ./artifacts/*
      - store_artifacts:
          path: ./debug.tar.gz
          destination: debug-artifact.tar.gz

  "store release artifacts":
    docker:
      - image: frolvlad/alpine-rust:latest

    steps:
      - checkout  
      - restore_cache:
          key: release-cache
      - run: |
          cp -R ./templates ./artifacts/
          tar c -zf release.tar.gz ./artifacts/*
      - store_artifacts:
          path: ./release.tar.gz
          destination: release-artifact.tar.gz

workflows:
  version: 2
  build:
    jobs:
      - build debug
      - build release
      - store debug artifacts:
          requires:
            - build debug

      - store release artifacts:
          requires:
            - build release
        
